### PR TITLE
Disambiguated 500 tokens of text in English

### PR DESCRIPTION
**Pull request by amuritna**
Source of raw text: https://en.wikipedia.org/wiki/Interstate_75

### CODE REVIEW

**Comment by wei2912** [comment]
Please add a MANIFEST file similar to that in https://github.com/apertium/apertium-eng/pull/4#merged-event. I haven't checked the texts yet, but will do so soon.

**Comment by amuritna** [comment]
Done. However, I'm not sure if it's in the right format ... is author=wikipedia and style=encyclopedia correct?

**Comment by amuritna** [comment]
I've updated the manifest file, the handtagging (I'll be better in the future!), and the dictionary. I remembered southward already being in the dictionary, but I re-checked and it seems like I was mistaken.

I'm not sure what I should do about "adding [bedroom] as an adjective", though. Do I go back to the handtagging and modify the noun tag into an adjective tag? Do I go to the dictionary and add it as a possible adjective, a "maybe__adj"? (Except "maybe__adj" has never been used in the dictionary, I just checked.) Or is "expensive__adj" the proper label? (I'm not sure what "expensive__adj" means, though, and I didn't have much luck finding an answer on it on the Apertium wiki or the rest of the internet.) Sorry for asking so much questions!

**Comment by ftyers** [comment]
I don't think it's a good idea to add bedroom as an adjective.

**Comment by amuritna** [comment]
Perhaps adding "bedroom community/communities" as a phrase would be a better idea?

**Comment by amuritna** [comment]
So, is this good/ready to merge? If not, what can I do to improve its quality?

**Pull request closed without merging**
